server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  datasource:
    username: user
    password: password
#    url: jdbc:postgresql://localhost:5432/polardb_catalog
    url: jdbc:postgresql://polar-postgres:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

management:
  endpoints:
    web:
      exposure:
        include: refresh

polar:
  greeting: "Welcome to the catalog from the config server"