polar:
  greeting: "Welcome to the catalog from the config server"

spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5

  management:
    endpoints:
      web:
        exposure:
          include: refresh